[pytest]
testpaths       = tests
addopts         = -v --tb=short --strict-markers
                  --cov=.
                  --cov-report=term-missing
                  --cov-report=html:tests/coverage_html
                  --cov-fail-under=80
                  --cov-config=.coveragerc
                  --ignore=dist
                  --ignore=build
filterwarnings  = ignore::ResourceWarning

markers =
    unit:        Tests unitarios puros (sin I/O externo)
    integration: Tests de integración (DB real, TestClient)
